# Generated by Django 2.0.9 on 2019-01-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.TextField()),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('content', models.TextField()),
                ('reporting_date', models.DateField()),
            ],
            options={
                'managed': True,
                'db_table': 'things',
            },
        ),
    ]
