# Generated by Django 2.0.9 on 2019-01-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='who',
            new_name='name',
        ),
    ]
