# Generated by Django 2.0.9 on 2019-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0002_auto_20190129_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='reporting_date',
            field=models.DateTimeField(),
        ),
    ]
