# Generated by Django 2.1.5 on 2019-03-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0003_auto_20190129_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reporting_date', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reporting_date', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tackle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField()),
                ('content', models.TextField()),
                ('thing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daepo_app.Thing')),
            ],
            options={
                'db_table': 'tackles',
                'managed': True,
            },
        ),
    ]
