# Generated by Django 2.1.5 on 2019-03-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0004_chat_request_tackle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tackle',
            options={'managed': False},
        ),
    ]
