# Generated by Django 2.1.5 on 2019-03-14 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0005_auto_20190313_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tackle',
            options={'managed': True},
        ),
    ]
