# Generated by Django 2.1.5 on 2019-03-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daepo_app', '0006_auto_20190314_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='reporting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='reporting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tackle',
            name='reporting_date',
            field=models.DateTimeField(),
        ),
    ]
